# Generated by Django 5.1.3 on 2024-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='assign_project',
        ),
        migrations.AddField(
            model_name='member',
            name='assign_project',
            field=models.ManyToManyField(related_name='member', to='api.project'),
        ),
    ]
