# Generated by Django 5.1.3 on 2024-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_step_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
