# Generated by Django 5.1.3 on 2024-11-29 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_step_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
