# Generated by Django 5.1.3 on 2024-11-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resource_step_resource_used_resourceallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
    ]
