# Generated by Django 5.1.3 on 2024-11-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_step_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceallocation',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project',
        ),
        migrations.AlterField(
            model_name='step',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceAllocation',
        ),
    ]
