# Generated by Django 5.1.3 on 2024-11-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_name_resourceallocation_resource_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceAllocation',
        ),
    ]
