# Generated by Django 5.1.3 on 2024-11-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_resource_resourceallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceallocation',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project',
        ),
        migrations.AddField(
            model_name='step',
            name='time_used',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceAllocation',
        ),
    ]
