# Generated by Django 5.1.3 on 2024-11-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_resourceallocation_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='hours', max_length=20)),
                ('total_capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.FloatField()),
                ('utilized_amount', models.FloatField(default=0)),
                ('remaining_amount', models.FloatField(blank=True, null=True)),
                ('allocated_time', models.FloatField()),
                ('utilized_time', models.FloatField(default=0)),
                ('remaining_time', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='api.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='api.resource')),
            ],
        ),
    ]
