# Generated by Django 5.1.3 on 2024-11-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_resource_resourceallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='assign_project',
            field=models.ManyToManyField(related_name='members', to='api.project'),
        ),
    ]
