# Generated by Django 5.1.3 on 2024-11-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_member_assign_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='assign_project',
            new_name='project',
        ),
    ]
