# Generated by Django 5.1.3 on 2024-12-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_assign_project_member_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceallocation',
            name='resource',
        ),
    ]
