# Generated by Django 5.1.3 on 2024-12-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_resourceallocation_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
    ]
